title: Protonium Docs
description: Documentation for the Protonium Language
baseurl: "/Protonium"
url: "https://sid200.github.io"

# Build settings
remote_theme: pmarsceill/just-the-docs
# highlighter: none
# highlight_theme: dark2
# color_scheme: dark
aux_links:
  # js functions in _includes/head_custom.html
  "Lights On!":
    - "javascript:(lightify())"
  "Lights Off!":
    - "javascript:(darkify())"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
